name: Hello Workflow

on: 
  push 

jobs: 
  Hello-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World 
        run : echo "Hello, Github Actions!"  
      
      - name: checkout code
        uses: actions/checkout@v4 

