name: Hello Workflow

on: push 

jobs: 
  Hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World 
        run : echo "Hello, Github Actions!"  
      
      - name: checkout code
        run : Actions/checkout@v4 

